### ISSUE TITLE
Parser errors related to redundant brackets

### ISSUE THREAD

**Issue by ThereforeGames** [bscotch/stitch#122]
Hi,

The Stitch parser seems to disallow redundant brackets even though they are considered valid GML. Here's an example:

`
DEBUG 01:56:32.903 [PARSER] SYNTAX ERROR Redundant input, expecting EOF but found: } t:/code/gamemaker/demoncrawl/scripts/vigenere_ascii/vigenere_ascii.gml {"image":"}","startOffset":1336,"endOffset":1336,"startLine":43,"endLine":43,"startColumn":1,"endColumn":1,"tokenTypeIdx":136,"tokenType":{"name":"EndBrace","PATTERN":{},"CATEGORIES":[{"name":"Separators","PATTERN":{},"tokenTypeIdx":20,"CATEGORIES":[],"categoryMatches":[33,34,35,36,45,46,106,107,108,109,110,127,128,131,132,133,134,135,136,137,138,144,146,148,149,151],"categoryMatchesMap":{"33":true,"34":true,"35":true,"36":true,"45":true,"46":true,"106":true,"107":true,"108":true,"109":true,"110":true,"127":true,"128":true,"131":true,"132":true,"133":true,"134":true,"135":true,"136":true,"137":true,"138":true,"144":true,"146":true,"148":true,"149":true,"151":true},"isParent":true}],"tokenTypeIdx":136,"categoryMatches":[],"categoryMatchesMap":{},"isParent":false,"POP_MODE":true}}
`

[This particular script came from GMLscripts.com](https://www.gmlscripts.com/script/vigenere_ascii) and was loaded into my project prior to GameMaker's support for `function()`. It was auto-converted to the new syntax and apparently ended up with an extra pair of brackets.

Should these brackets be removed? Well, yes, but I think Stitch ought to treat this as a warning instead of an error. That is, unless parity with the GM compiler is not a development priority - no worries if so (it's your software after all), but it probably needs to be stated clearly on the project page.

Also, I'm not 100% sure of this, but I think redundant brackets are creating a lot of error messages downstream when they occur inside of a switch-case statement. For example, here's some old code from my misguided youth:

```
case someval:
{
	whoa_man();
}
break;
```

This is causing the parser to throw a bunch of errors at every subsequent case statement.

Let me know if I can provide more diagnostic information. Thanks.

**Comment by adam-coster** [comment]
Stitch is intended to be *close* to parity with GameMaker, except for features that are:

- Difficult to implement, and
- Something we don't use internally

Parser logic is super complicated, and this is one of those things that every time I tried to get to work would end up with stack overflows or other problems. We only used extraneous brackets in a few places in our code, so it was much easier to just remove those from the code than to support them in the Stitch parser.

It's not obvious what GML features Stitch doesn't support, since it supports all of the features that we do use. But you're right that including this item and other known differences in the docs would be a good idea.

The other major difference is that Stitch can only parse macros that are set to complete expressions (not statements, and not things that are invalid as standalone expressions). It's the same kind of problem as the extra brackets, just a lot worse: macros are technically allowed to break parser rules since they're only supposed to be parsed at compile-time, and since we only use macros for expressions anyway I haven't had to solve that problem.

Anyway,  I'll get the README updated to make sure it has a section on known differences between Stitch and the GameMaker IDE!

**Comment by adam-coster** [comment]
Although for this specific use of extraneous brackets there might be an easy change to the parser that would support it. I'll take a look next time I'm working on it.

**Comment by ThereforeGames** [comment]
I appreciate it, thanks!

I can sympathize with the complexity of writing a parser for GML. I've been using this language since GM5 or so--and it's really changed and improved a lot over the years--but it still has some idiosyncrasies leftover from those "wild west" days when you could do whatever you wanted with regard to syntax.

Whether you want to support things like redundant brackets or valid-but-also-invalid macro statements is really up to you. I think it would be beneficial in the sense that when new people try Stitch, they load up one of their existing projects and will be delighted when it just works. On the other hand, it's not really your responsibility to encourage or support some of the weird coding practices from GameMaker's early days.

**Comment by adam-coster** [comment]
The latest version of Stitch now includes some documentation for unsupported GML features, and also allows for curly braces to be used in `switch` conditions.

**Comment by NyakoFox** [comment]
> The latest version of Stitch now includes some documentation for unsupported GML features, and also allows for curly braces to be used in `switch` conditions.

Hello, is this still the case? I'm also getting an error because of braces inside of a case.

![image](https://github.com/bscotch/stitch/assets/87289390/cad29910-7a61-4484-a945-1eede01da872)

**Comment by adam-coster** [comment]
Confirmed: curly braces still (or again?) cause a parser error in switch cases.

I'm not sure what to make of it -- the logic looks like it *should* allow for curlies around switch cases, but it definitely doesn't.

Since those are non-functional anyway I can't spend the time trying to sort that out, but if anyone else can I'm happy to take a PR!
