### ISSUE TITLE
Add the ability to add sprites via the Resource Tree

### ISSUE THREAD

**Issue by BscotchSeth** [bscotch/stitch#185]
Similar to being able to add objects, scripts, and groups, I want to be able to add sprites to the project via this context menu.

![image](https://github.com/bscotch/stitch/assets/26627245/59507aba-0012-4ac3-9e64-35594f6aa1b2)

To add a sprite, I want to:

* Navigate to the folder that contains the sprite's files
* Select one or more images, which will become the subimages for the sprite. All the selected images must be the same dimensions.
* Choose the name of the sprite... SOMEHOW? Alternatively Stitch could use magic to come up with the name for me, based on the names of the subimages I chose.

**Comment by adam-coster** [comment]
v1.57.0 adds "New Sprite..." to the resource tree context menu! It's a bit of a hack to re-use parts of the image pipeline, so we'll have to keep an eye out for jank.

THINGS TO NOTE:

- It'll ask for a "Sprite folder" rather than individual source images. This is the same strategy we use for all of the other Stitch sprite stuff -- you'll need to already have a folder representing the sprite source, containing one or more PNG images of identical size (the frames for that sprite). Anything else will result in an error.
- Frame names don't matter (they get converted into GUIDs), except that however they sort in the source folder based on their names is the same order they'll end up in in the imported Sprite
- You'll have the option to crop/bleed the images (same technique as in the art pipeline). These are applied to the SOURCE images before import, so keep that in mind!

Next I'll need to add a context menu option for existing sprite assets to re-import them. That would work the same way -- you'd point to a source folder, whose images would fully replace the frames on the existing sprite (the same way the image pipeline works).

**Comment by adam-coster** [comment]
Completed in 1.58.0, with the ability to replace an existing sprite's frames.
