### ISSUE TITLE
Can't start game through F5

### ISSUE THREAD

**Issue by NyakoFox** [bscotch/stitch#187]
Despite having v2023.8.2.108 installed, it doesn't seem to work for me.

![image](https://github.com/bscotch/stitch/assets/87289390/067fc47d-cbff-46e6-b511-eb644e514937)

![image](https://github.com/bscotch/stitch/assets/87289390/b993dbc2-5815-4a57-b6c0-6eccfe83d707)

This happens on multiple projects.

Looking into `releases-summary.json`, it looks like runtime version `2023.8.2.152` is grouped with IDE version `2023.8.2.106`, where `2023.8.2.108` is nowhere to be seen.

**Comment by adam-coster** [comment]
Looks like an attempt to optimize made it possible for some IDE entries to end up unpaired with any runtime (only happens to exactly two of all of the IDE versions, so that's weird!)

The RSS feeds don't actually specify which runtime is paired with which IDE, so I just assign the one that was published the closest to the same time. This issue seemed to have something to do with a few IDE versions best matching with the *same* runtime version, which my previous logic didn't account for.

Should be resolved in `v1.55.10`
