### ISSUE TITLE
Launching the Game Maker IDE through Stitch doesn't preserve your config settings.

### ISSUE THREAD

**Issue by BscotchSeth** [bscotch/stitch#196]
Replication:

- Launch Game Maker through Stitch.
- Change the config to 'dev'.
- Close Game Maker.
- Reopen Game Maker through Stitch.
- See that the config has reverted to 'Default' and must be manually changed back to 'dev'.

**Comment by adam-coster** [comment]
Stitch just launches the IDE directly (without passing any commandline arguments or anything) and doesn't touch the IDE settings, so I'm not sure why this would happen.

My guess is this has something to do with the fact that Stitch makes a copy of each runtime and launches that (enabling you to have multiple IDE installs available at once instead of re-installing when switching versions).

The GameMaker IDE settings are still shared between versions, since there's no way to change that on a per-version basis.

Still, what I'd expect to see is that no matter how you open an IDE version you'd end up with the same config you last had.

Will definitely require some digging to sort out.

**Comment by adam-coster** [comment]
Pretty sure we determined that this is a GameMaker IDE bug so I can close this, right @BscotchSeth ?

**Comment by BscotchSeth** [comment]
Confirmed!
