### ISSUE TITLE
Support reusing the same terminal tab, so you can pop GM terminal out as a floating window

### ISSUE THREAD

**Issue by pr0te** [bscotch/stitch#203]
Kind of a bad title. Let me explain!

Newer vscode versions can now open the terminal inside the editor as a tab, and that editor tab can now become a floating window that can be moved to another monitor for example. I would love to be able to have the GM runner terminal on another monitor, which can be done right now, but you have to set it up again every time you run the game, as running the game adds a new terminal to the bottom panel.

**Comment by adam-coster** [comment]
I like this idea! I'm not sure how I'd go about this, but more generally I need to revisit how the terminal is being used at some point. I'm not sure what is the range of VSCode features that I could be leveraging for this part of the extension.

Unfortunately this won't be a high priority for internal development until we have a specific need for it, but I'm open to additional comments and even PRs! Before anyone goes through the work and creates a PR, though, I want to make sure we're in agreement about intended behavior. Discussion should continue on this Issue.

**Comment by pr0te** [comment]
Thanks. Do let me know if anything is unclear. I would love to have this functionality at some point!

**Comment by adam-coster** [comment]
I'm working on an alternative to using the terminal, so that you'd get a tab with the output as a custom web view.

That'll allow me to add custom color highlighting and some interesting search/filter features. Should be out as an opt-in alpha next week.

**Comment by pr0te** [comment]
That sounds pretty interesting. I'll definitely check that out.

**Comment by adam-coster** [comment]
The latest version includes this as an initial draft if you want to try it out!

- *(Note that the "Project" panel, in the Stitch sidebar has been renamed to "Resources")*
- There's a new panel in the Stitch sidebar called "Runner". The "Play" buttons there are the same as what was in the "Project" panel. By default they'll still run via a new terminal each time.
- There are some new settings for this feature in VSCode. In your settings, search for "stitch run" or "stitch runner" to see them. In particular, if you disable "Run: In Terminal" you'll be opting in to using the new panel instead of the terminal!

Currently there aren't any new features -- it just moves everything into a panel. The logs are searchable there, which is the main thing.

You can keep the panel there, or drag it into your secondary panel.

Will this new feature resolve this request? I'll be expanding the functionality of this Runner panel, but that's unrelated to the original request.

**Comment by pr0te** [comment]
This is a really cool feature. I just tried it out and I can see this being really useful! However, it doesn't resolve the request because this panel cannot be popped out into a window, like you can with editor tabs now. What I dream of every night is to have this terminal in a separate window, on my secondary monitor. That way it never gets in the way, and I can see much bigger view.

Btw, clickable error locations that jump to the file and line would be lovely!

**Comment by adam-coster** [comment]
While I'm pretty sure I can make the terminal reusable so that you can pull it out, I think that the new panel (with all of its incoming features) is stuck in the main window (unless VSCode someday lets you pop panels out).

I'm working on clickable links and color highlighting right now!

**Comment by pr0te** [comment]
All good news to me! Thanks a lot for what you're doing with this. Please do let me know if you manage to make the terminal reusable. Would be killer at least for my workflow!

**Comment by adam-coster** [comment]
The latest version should now reuse the same terminal, unless you have the "kill others on run" setting on false (since you can't send a command to a terminal that's already running the game).

Please make new Issues if you run into any problems!

**Comment by pr0te** [comment]
You're a legend. Thank you so much. It works!
