### ISSUE TITLE
looks like a global but is not declared anywhere

### ISSUE THREAD

**Issue by NonZeroMon** [bscotch/stitch#219]
Just started using Stitch today, and this seems like the perfect tool I have been hoping for.

I declare a struct variable in the create event of an object and then I call a function that reference's that specific declared struct from the object. 

__ looks like a global but is not declared anywhere.
![image](https://github.com/bscotch/stitch/assets/20160611/80466d26-fe4f-4250-bae4-c72824eba1b6)

![image](https://github.com/bscotch/stitch/assets/20160611/7e44acf6-2be8-41ce-926d-b550f1f6518d)

The same error also happens for mv_get = function() which is initially being declared in the gp_create_move_and_collide() function as well

**Comment by adam-coster** [comment]
Is that function also defined in the same Create event?

**Comment by NonZeroMon** [comment]
The function is defined in a script. I did figure out that if I put /// @self Id.Instance.object before the function definition in the script it would make it recognizable.

The question now, is there a way a to disable warning messages in Stitch?

**Comment by adam-coster** [comment]
Stitch takes something of a more opinionated approach to GML so that it can give you as much help as possible. It's sorta like having Feather enabled in the GameMaker IDE, though Feather is a lot more configurable and covers a lot more kinds of problems.

I do want to provide more options for customizing the warning/error messages in Stitch, but since we want to *ensure* those messages for our own projects that isn't a high priority yet.
