### ISSUE TITLE
Stitch does not recognise project

### ISSUE THREAD

**Issue by tichaelmurvey** [bscotch/stitch#239]
Windows 10 with VSCode 1.8.8

I have opened a GM Studio project in VS Code.

Stitch does not recognise the project, or show the "Projects" pane.

I tested this with a project made using stitch's New Project function and with an existing default project made in GM studio.

Not sure if I'm missing something but I've followed all the instructions in the video tutorial and looked all through the settings, so I have to assume this is a bug.

See screenshots:
<img width="1128" alt="2024-05-01_16-31-02" src="https://github.com/bscotch/stitch/assets/16234792/1195f475-2e35-4ddd-bcac-c6e6fb7e9eaf">

<img width="1128" alt="2024-05-01_16-30-52" src="https://github.com/bscotch/stitch/assets/16234792/40d1c456-0ff1-4a91-be8b-fc147822d314">

**Comment by adam-coster** [comment]
Ah, there have been some changes to Stitch since the video went up:

- Stitch now only loads one project at a time (per VSCode window). If the folder you open in VSCode has multiple GameMaker projects you should get a prompt to pick the one you want to load.
- The "Project" panel has been renamed to "Resources", to better reflect its actual purpose (and since you can no longer load multiple projects at once).

From your first screenshot I see that there are resources listed -- if you navigate through them are you able to open your project files?

**Comment by tichaelmurvey** [comment]
Ah, that was the issue thank you! I assumed it would be something like that.

Thanks for making this extension, it rules!
