### ISSUE TITLE
"Could not load project ... ← Resource ... already exists" error if there are resourses' names differ only in letter case

### ISSUE THREAD

**Issue by AlexGovr** [bscotch/stitch#244]
Hi!
Not a big issue but still seems to be a bug.

### The issue
My project had two resources: a sprite named Big_Tree and a tileset named Big_tree. Names are almost identical yet differ only in one letter case. This causes an error with message "Could not load project <project_name> ← Resource big_tree already exists"

The issue can be easily fixed by using "non-case-sensetive" different names. In my case I renamed those two assets to sBig_Tree and tsBit_Tree

**Comment by adam-coster** [comment]
Due to some legacy weirdness and platform-specific behavior around casing, Stitch just takes the simplest and most-compatible strategy of requiring all assets to be uniquely named in a case-independent way. Unfortunately that is baked into a lot of Stitch functionality, so it'll probably have to stay that way.

Asset type prefixes are useful in GameMaker anyway since everything is global.
