### ISSUE TITLE
cannot open 2024.06.2.162

### ISSUE THREAD

**Issue by net8floz** [bscotch/stitch#253]
stitch open --ide 2024.06.2.162 

hello i am unable to open this version of gm. maybe they named it weird. 

Making sure that IDE v2024.06.2.162 is installed...
file:///C:/Users/net8f/.nvm/versions/node/v21.7.1/bin/node_modules/@bscotch/stitch/node_modules/@bscotch/stitch-launcher/dist/lib/GameMakerIde.js:46
        throw new GameMakerIdeError(message, code);
              ^

GameMakerIdeError: Could not find runtime version 2024.06.2.208
    at assert (file:///C:/Users/net8f/.nvm/versions/node/v21.7.1/bin/node_modules/@bscotch/stitch/node_modules/@bscotch/stitch-launcher/dist/lib/GameMakerIde.js:46:15)
    at GameMakerIde.openProject (file:///C:/Users/net8f/.nvm/versions/node/v21.7.1/bin/node_modules/@bscotch/stitch/node_modules/@bscotch/stitch-launcher/dist/lib/GameMakerIde.js:64:9) {
  code: 'RUNTIME_NOT_FOUND'
}

Node.js v21.7.1

**Comment by adam-coster** [comment]
Huh. I haven't tried that version. Does it work if you use `2024.6.2.162` (that extra zero really shouldn't be in there, but I don't know what subset of the GameMaker data includes it).

**Comment by net8floz** [comment]
Hello sorry for the delay, no it does not work it fails even earlier. In the mean time I've just installed GM regular like a chump. Again I think this is because yyg named this release weird.  I read around chatrooms that even the IDE fails to install with a runtime but this should be taken as a rumor.

**Comment by adam-coster** [comment]
Lol classic. Trying to fix this on the Stitch side doesn't seem worth the effort, so hopefully this is a one-off problem! We skipped that version since it has some audio bugs.

I'll note that the latest beta IDE version (`2024.800.0.618`) and its runtime are the first in a while to pass all of our tests, and resolves some of the new problems introduced by recent runtimes (audio issues in particular). So if you can I recommend trying that version instead!
