### ISSUE TITLE
All variables say "Looks like a global but is not declared anywhere."

### ISSUE THREAD

**Issue by nyius** [bscotch/stitch#255]
Hey!
I'm new to Gamemaker & stitch and I am having some trouble getting everything working properly.
I have the extension working fine in that I can edit the gml code and see my project & run it from inside VS code, but for some reason all of my variables that are created in a different file are throwing the errors below

![image](https://github.com/user-attachments/assets/219a8f97-207b-45da-9d97-81c6ad10713c)

If I right click on any of those erroring variables, for example jump_timer_initial and select "Go to type definition", it says that none can be found 
Just wondering if I missed setting up something or where I'm going wrong with that

Edit: it seems like just the variables inside any script files in the 'scripts' folder that are throwing the errors, whereas all variables inside events (create, step, etc) have no problem and work perfectly 

Thanks!

**Comment by adam-coster** [comment]
Welcome to GameMaker!

Stitch is a "static analysis tool", so it's more strict than GML (stuff that is valid GML might not be easy enough to analyze in Stitch, so it'll present an error of some sort even though the code works).

Tracking variables is a difficult analysis problem, since two variables can have the same name but not mean the same thing. Scope complicates things even further: Stitch has to be able to tell if a variable is *local*, an *instance variables*, or a *global*. Sometimes it's unambiguous, but often it's not.

In your code you have that `jump_timer` variable. The fact that Stitch is telling you it looks like a global means that Stitch is unable to find a local or instance variable with the same name in the same scope, so it's assuming it must be a global, but then cannot find that global either. I don't have enough context to know where `jump_timer` is coming from here, or where the code you're showing is relative to that, so I'm not sure specifically why it's not found.

The most common scenario that creates this is inside functions. Since functions can be called anywhere, you'll often define them in a *different context* from where they're called. In that new context you'll then reference variables *where* it will be called, but Stitch doesn't know where you intend to call the function (nor if you'll only call the function in specific places).

For example:

```js
// In a Script
function initialize_player(){
  name = "Default Name";
  x = 0;
  animation_state = 3;
}

// In the Create event of o_player
name = "";
x = 0;
animation_state = 0;
```

In the code above you'll get the same error for all of those instance variables, because the `initialize_player()` function *doesn't know its context is `o_player`*.

There are lots of approaches to solving it, but GameMaker and Stitch both support the `@self` JSDoc tag for specifying context for a function. You have to specify it using valid GameMaker ("Feather") types, which are pretty strict and take some getting used to (in Stitch, if you right-click a variable name you can copy its Feather type, and autocompletes in Stitch will also help).

So if I updated the prior code to this I'd solve the problem:

```js
// In a Script
/// @self {Asset.GMObject.o_player}
function initialize_player(){
  name = "Default Name";
  x = 0;
  animation_state = 3;
}

// In the Create event of o_player
name = "";
x = 0;
animation_state = 0;
```

**Comment by nyius** [comment]
> The most common scenario that creates this is inside functions. Since functions can be called anywhere, you'll often define them in a different context from where they're called


This was my problem exactly, it was in all of my custom functions where the errors were. That definitely makes sense for how it's difficult for Stitch to know which context relates to each variable inside of my functions.
Using `@self` JSDoc seemed to make the problem go away! 
Thanks for your help
