### ISSUE TITLE
Add option to toggle off problems, or fix this accessor problem at least?

### ISSUE THREAD

**Issue by mosquitobird11** [bscotch/stitch#256]
First off, I really love this extension. It enables such a higher quality of life when I can work directly on gm projects AND have access to copilot. However, I have quite a bit of nonsense / wrong problems being flagged by stitich:
![image](https://github.com/user-attachments/assets/c01cfcc4-990c-4e41-af08-d391ee6c8074)
from chaining accessors together. 

Is there a way to globally disable problem flagging / underlining from Stitch? I don't find it to be valuable in my work, but all of the other features are 💯

**Comment by adam-coster** [comment]
I'm glad you (mostly) like the extension! I don't have any plans to add a setting for disabling Stitch issues, though I know it can get annoying (especially for old projects, and for projects not making use of JSDoc/Feather comments). In principle it wouldn't be difficult to add such a setting, I'd just have to find time to do it since it's not a use case we need on our team.

VSCode does have a global setting to hide all problems, so that'll do the trick if you aren't finding any of the Stitch issues helpful.

![image](https://github.com/user-attachments/assets/6f152efc-5310-451a-960e-c30dfd95e419)

The best-practice solution is to add type information via JSDocs so that Stitch can understand your code and give you proper autocompletes without showing extraneous errors. (Though it's possible that the specific case you're showing here is from Stitch failing to use a typed value properly -- in that case please let me know!)

**Comment by adam-coster** [comment]
Following up to say that I double-checked Stitch's parsing of function calls immediately followed by a dot-accessor, like your `top().move_to`. It works properly in my test cases, so long as the function has a struct return type. So either this is an edge case that I'll need more info on, or the `top()` function would need to be updated to have an explicit or inferrable return type.

**Comment by mosquitobird11** [comment]
Just checked back on this, and still using Stitch every day! Thanks for the tips about vscode and jsdoc, I think that is sufficient 😄 ! I am having issues trying to get stitch to understand some struct-scoped variables that are being accessed but defined only in parent structs though 🤔 but I will keep trying to figure that out. E.g.:
```
function Parent(_config = {}){
    size = _config[$ "size"] ?? 28;
}

function SubClass(_config = {}) : Parent(_config) constructor {
    function thing(){
        return size * 2;  // <-- Struct says size is undeclared
    }
}
```

**Comment by adam-coster** [comment]
I'm pretty sure that's a current limitation of Stitch (though I haven't touched the parser for a while). I don't think I figured out a way to model inheritance -- all of our current code bases started before constructors even existed in GameMaker, so our design patterns don't make much use of constructors and inheritance. It's on my list of "someday..." features.

*(In your code sample your `Parent` function is missing the `constructor` keyword, but I'm guessing that's just a mistake in the example rather than in your game code.)*
