### ISSUE TITLE
Error running command stitch.openIde

### ISSUE THREAD

**Issue by HaselmutGames** [bscotch/stitch#260]
Hello,
I recently discovered Stitch and I was trying to open GameMaker from the VSCode using Stitch but I keep getting the error in the pic. (Note: if I run the project everything works and the game launches, only opening GM doesn't work)
Is this known or am I missing something?
- I tried running VSCode as admin because I thought the problem was a permission problem for the C:\Program Files\Common Files folder but it didn't help.
![image_2024-11-07_002507183](https://github.com/user-attachments/assets/f498f8cb-05ab-4d4d-a914-02eda6163c09)

**Comment by adam-coster** [comment]
Since GameMaker can be installed to various locations, Stitch does a scan of possible locations, looking for executable files with the expected names. It looks like while Stitch is trying to scan your Program Files for GameMaker installs it's looking into some kind of protected folder (that "Gemeinsame Dateien" folder) and then erroring out.

Does that folder have some kind of admin permissions on it or something?

I'll take a look at the scanning logic and see if there's a way to have it fail gracefully in this sort of case.

**Comment by adam-coster** [comment]
I think this is resolved in 1.72.0. Please let me know if it works!

**Comment by HaselmutGames** [comment]
Yes! I've just tried it and it works, thank you soooo much for the fast help! Much appreciated.

**Comment by adam-coster** [comment]
Rad, glad to hear it!
