### ISSUE TITLE
Error running command stich.openIde: Could not find version ... after installation

### ISSUE THREAD

**Issue by schmooblidon** [bscotch/stitch#262]
Can't open my project, no matter which version is set. I see it install the version, but fails when trying to open. I have gamemaker usually installed in D:/Program Files but it still uses C:/ProgramData for w/e it uses ProgramData for, so perhaps that is relevant. Is there any way to point it in the right direction?

**Comment by adam-coster** [comment]
Stitch just looks in C:/, but GameMaker installs to the last drive it installed to by default, so in this case Stitch can't find it after install.

If you don't mind installing to C:, you can do a manual install of GameMaker once and ensure you set it to C:, and after that it'll keep installing where Stitch can find it.

**Comment by schmooblidon** [comment]
Yep this works thanks. I typically install to D for space reasons, but honestly gamemaker is pretty small, so its not really an issue. Thanks for the tool, gunna make it much easier to work on multiple projects <3

**Comment by adam-coster** [comment]
@schmooblidon Yeah, we have people on the team that also tend to do that. GameMaker still puts the big stuff (runtimes) on your C drive, though, so installing the IDE to other drives doesn't help all that much.

Note that Stitch keeps a copy of each IDE you install via Stitch, so that you can switch back and forth between versions without having to re-install. So if you've got space concerns and change versions frequently you may want to clean those up every now and then. You can get to Stitch's cache with the "Stitch: Open Stitch Location" command.

![image](https://github.com/user-attachments/assets/1185e504-3cb2-4fa4-8275-cc06837f9058)
