### ISSUE TITLE
When non-loadable projects are found and skipped they should still be reported

### ISSUE THREAD

**Issue by WangleLine** [bscotch/stitch#48]
It's a Gamemaker project from around 2020, not sure which version (yyp doesn't seem to contain the ide or runtime versions)
https://drive.google.com/file/d/1wzjDCJrwBRYU93WNzgiU3bCSVC3lZZsH/view?usp=sharing

![Stitch_HmVJNanXCr](https://user-images.githubusercontent.com/34343336/230516303-a1a78cb9-2b2c-4692-a15a-4613a726673b.png)

**Comment by adam-coster** [comment]
Stitch has no nuance when it comes to finding projects and reporting whether or not it found any.

It basically scans for `.yyp` files starting from the folder you specify, and then checks each one it finds to see if it matches the expected format for recent GameMaker versions. It just skips `.yyp` files that don't match that format, rather than reporting any errors.

To keep Stitch maintainable we try to keep its features compatible with the latest versions of GameMaker without also trying to maintain backwards compatibility.

**Comment by WangleLine** [comment]
Oh yeah I wasn't super expecting it to work with versions this old, but the message it returned felt wrong

**Comment by adam-coster** [comment]
@WangleLine Yeah you're totally right about that! It really should show some sort of indication that it found project files but couldn't load them.

**Comment by adam-coster** [comment]
Closing due to deprecation of Stitch Desktop in favor of [Stitch for VSCode](https://tinybs.co/stitch-vscode).

See #138 for details.

(Note that the VSCode extension does provide a warning when a project was found but could not be loaded!)
